name: project card event hooks

on:
  project_card:
    types:
      - created
      - moved
      - converted
      - edited
      - deleted

jobs:
  show-project-card-events:
    name: show project card event
    runs-on: ubuntu-latest
    steps:
      - name: show project github event
        env:
          GHC: ${{ github }}
        run: echo $GHC
