name: project event hooks

on:
  project:
    types:
      - created
      - updated
      - closed
      - reopened
      - edited
      - deleted

jobs:
  show-project-events:
    name: show project event
    runs-on: ubuntu-latest
    steps:
      - name: show project github event
        env:
          GHC: ${{ github }}
        run: echo $GHC
