name: project event hooks

on:
  project:
    types: 
      - created
      - updated
      - closed
      - reopened
      - edited
      - deleted

jobs:
  show_project_events:
    name: show project event
    runs-on: ubuntu-latest
    steps:
      - name: show project github event
        env:
          GHC: ${{ toJson(github) }}
        run: echo $GHC
