name: pull request(open/close/edit/synchronize/ready-for-review/review-requested)
on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - synchronize
      - ready_for-review
      - review_requested

jobs:

  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: show foo
        run: echo foo
      - name: show env
        env:
          ENV_CTX: ${{ toJson(env) }}
        run: echo "$ENV_CTX"
  bar:
    name: bar
    runs-on: ubuntu-latest
    needs: foo
    steps:
      - name: show bar
        run: echo bar
      - name: show github
        env:
          GHC: ${{ toJson(github) }}
        run: echo "$GHC"
      - name: store github to file
        env:
          GHC: ${{ toJson(github) }}
        run: echo "$GHC" > github.json
      - name: upload github as archive
        uses: actions/upload-artifact@v1
        with:
          path: github.json
          name: github.json
  baz:
    name: baz
    runs-on: ubuntu-latest
    needs: bar
    steps:
      - name: show baz
        run: echo baz
      - name: show job
        env:
          JOB_CTX: ${{ toJson(job) }}
        run: echo "$JOB_CTX"

  comment:
    name: hello comment
    runs-on: ubuntu-latest
    needs: baz
    steps:
      - name: create comment
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URI: ${{ github.event.pull_request._links.comments.href }}
          COMMIT: ${{ github.sha }}
          FLOW: ${{ github.workflow }}
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
        run: |
          curl -i -X POST "$COMMENT_URI" -H 'Authorization: Bearer $TOKEN' \
              --data '{"body":"${COMMIT}\n---\n\n* flow - $FLOW\n* event - $EVENT_NAME\n* action: $EVENT_ACTION"}'
