name: pull request(open/close/edit/synchronize/ready-for-review/review-requested)
on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - synchronize
      - ready_for-review
      - review_requested

jobs:

  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: show foo
        run: echo foo
      - name: show env
        env:
          ENV_CTX: ${{ toJson(env) }}
        run: echo "$ENV_CTX"
  bar:
    name: bar
    runs-on: ubuntu-latest
    needs: foo
    steps:
      - name: show bar
        run: echo bar
      - name: show github
        env:
          GHC: ${{ toJson(github) }}
        run: echo "$GHC"
      - name: store github to file
        env:
          GHC: ${{ toJson(github) }}
        run: echo "$GHC" > github.json
      - name: upload github as archive
        uses: actions/upload-artifact@v1
        with:
          path: github.json
          name: github.json
  baz:
    name: baz
    runs-on: ubuntu-latest
    needs: bar
    steps:
      - name: show baz
        run: echo baz
      - name: show job
        env:
          JOB_CTX: ${{ toJson(job) }}
        run: echo "$JOB_CTX"

  comment:
    name: hello comment
    runs-on: ubuntu-latest
    needs: baz
    steps:
      - name: create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          reaction-type: "+1"
          body: |
            ${{ github.workflow }}
            ===
            
            - ${{ github.sha }}
            - ${{ github.event.name }}
            - ${{ github.event.action }}
