name: release

on:
  push:
    tags:
      - v*.*.*
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: '13.0.2'
      - name: check out
        uses: actions/checkout@v2
  
      - name: cache gradle modules
        uses: actions/cache@v1
        env:
          cache-name: gradle-modules
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys:
            ${{ runner.os }}-gradle-

      - name: git tag
        run: git tag --list

      - name: verify release
        run: ORG_GRADLE_PROJECT_project_version=`git tag --list | head -n 1` ./gradlew showVersion verifyRelease

      - name: show env
        run: env | sort
  
      - name: show event
        run: cat $GITHUB_EVENT_PATH

      - name: release
        run: ORG_GRADLE_PROJECT_project_version=`git tag --list | head -n 1` ./gradlew assemble githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
