name: test

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - actions-*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      -
        name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: '13.0.2'
      -
        name: check out
        uses: actions/checkout@v2

      -
        name: cache gradle modules
        uses: actions/cache@v1
        env:
          cache-name: gradle-modules
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys:
            ${{ runner.os }}-gradle-

      -
        name: show github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: show job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: show steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      -
        name: test
        run: ./gradlew test    
