name: test

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      -
        name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: '13.0.2'
      -
        name: check out
        uses: actions/checkout@v2

      -
        name: cache gradle modules
        uses: actions/cache@v1
        env:
          cache-name: gradle-modules
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys:
            ${{ runner.os }}-gradle-

      -
        name: show tags
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN && \
          curl -i https://api.github.com/repos/mike-neck/java-github-actions-playground/git/tags \
              -H 'Authorization: Bearer $GITHUB_TOKEN' \
              -H 'Accept: application/vnd.github.v3+json'

      -
        name: test
        run: ./gradlew test    
